# Generated by Django 5.2.2 on 2025-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
